<HTML>
<Head>
	<Title>Products - Can't stop the Riats</Title>
	<link rel = "stylesheet" type = "text/css" href = "layout.css"/>
	<link rel="icon" type="image/png" href="favicon.png">
</Head>
<Body>
	<?php include "header.php"; ?>
	<div class = "container">
		<img src = "/img/comingsoon.png"/>

		<p>This product is coming soon. It's
		going to be mind blowing.</p>
		<button type="button">Add to Cart</button>
	</div>
</Body>
</HTML>