<HTML>
<Head>
	<Title>Products - Can't stop the Riats</Title>
	<link rel = "stylesheet" type = "text/css" href = "layout.css"/>
	<link rel="icon" type="image/png" href="favicon.png">
</Head>
<Body>
<?php
	$grid_size = 4;
	if($grid_size > 0)
	{
		echo "<div class = 'container'>";
			echo "<ul>";
			for ($i = 0; $i < $grid_size; $i++){
				if($i % 3 == 0 && $i > 0){
					echo "</ul>";
					echo "<ul>";
				}
				echo "<li>
							<div>
								<a href = 'serve'>
								<img src = '/img/comingsoon.png'/>
								</a>
							</div>
							<div>
								Products are coming soon!
							</div>
					  </li>";
			}
			echo "</ul>";
		echo "</div>";
	}
?>
</Body>
</HTML>