<HTML>
<Head>
	<Title>Sign Up! - Can't stop the Riats</Title>
	<link rel = "stylesheet" type = "text/css" href = "layout.css"/>
</Head>
<Body>
	<?php include "header.php"; ?>

	<div class = "container">
		<ul class = "signup-field-list">
			<h1>Welcome to Riats!</h1>
				<form name = "form-group" action = "signup-handler.php" method = "POST">
					<li>
						<input class = "form-control" type = "text" name = "username" placeholder = "Username (required)">
						<?php
							if($_SESSION["userAuthenticated"] === false && isset($_SESSION["userAuthenticated"])){
								echo "<span class = 'signup-error'>Not a valid e-mail</span>";
							}
							if($_SESSION["userExists"] === true){
								echo "<span class = 'signup-error'>This user already exists</span>";
							}
						?>
					</li>
					<li>
						<input class = "form-control" type = "password" name = "password" placeholder = "Password (required)">
						<?php
							if($_SESSION["passAuthenticated"] === false && isset($_SESSION["passAuthenticated"])){
								echo "<span class = 'signup-error'>Not a valid password</span>";
							}
						?>
						<div class = "pass-message">
						Password must be over 8 characters long and must contain 1 or more capital letter(s), 
						lowercase letters, and 1 or more number(s).
						</div>
					</li>
					<li>
						<input class = "form-control" type = "text" name = "mAddress" placeholder = "Address (required)">
						<?php
							if($_SESSION["mAddress"] === false){
								echo "<span class = 'signup-error'>Required field</span>";
							}
						?>
					</li>
					<li>
						<input class = "form-control" type = "text" name = "m2Adress" placeholder = "Address 2">
					</li>
					<li>
						<input class = "form-control" type = "text" name = "zCodeMA" placeholder = "Zip (required)">
						<?php
							if($_SESSION["zipAuthenticated"] === false && isset($_SESSION["zipAuthenticated"])){
								echo "<span class = 'signup-error'>Not a valid zip code</span>";
							}
							if($_SESSION["zCodeMA"] === false){
								echo "<span class = 'signup-error'>Required field</span>";
							}
						?>
					</li>
					<li>
						<input type = "submit" name = "submitButtonSignup" value = "Submit">
					</li>
				</form>
		</ul>
	</div>

	<?php include "footer.php"; ?>
	<?php session_destroy() ?>
</Body>
</HTML>